---
- name: Install apt packages
  hosts: localhost
  become: true

  tasks:
    - name: "Install system packages"
      ansible.builtin.apt:
        name:
          - jq
          - curl
          - apt-transport-https
          - ca-certificates
          - build-essential
          - cmake
          - llvm
          - libstdc++-12-dev
          - lld
          - clang
          - python-is-python3
          - lldb
          - libicu-dev
          - liblttng-ust-dev
          - libkrb5-dev
          - zlib1g-dev
          - ninja-build
          - gnupg2
          - gnupg
          - vim
          - bat
          - exa
          - google-chrome-stable
          - htop
          - linux-tools-common
          - linux-tools-generic
          - hwloc
          - libssl-dev
          - git
          - nmap
          - zlib1g-dev
          - hyperfine
          - tre-command
          - neofetch
          - bind9-dnsutils
          - wavemon
          - fio
          - iputils-tracepath
          - speedtest-cli
          - sqlite3
          - python3-debian
        state: present
