---
- name: Install deb packages
  hosts: localhost
  become: true

  tasks:
    - name: "Install vscode"
      ansible.builtin.apt:
        state: present
        deb: http://go.microsoft.com/fwlink/?LinkID=760868
