---
- name: Install aliases
  hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Alias ls -> exa
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: alias ls=exa
        state: present
        insertafter: EOF

    - name: Alias cat -> batcat
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: alias cat="batcat --no-pager"
        state: present
        insertafter: EOF

    - name: Alias python -> python3
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: alias python=python3
        state: present
        insertafter: EOF
