---
- name: Configuration
  hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Neofetch
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: neofetch
        state: present
        insertafter: EOF

    - name: Add direnv hook
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: "eval \"$(direnv hook bash)\""
        state: present
        insertafter: EOF
