---
- name: Configure git
  hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Default branch
      community.general.git_config:
        name: init.defaultBranch
        scope: global
        value: main

    - name: Auto setup remote
      community.general.git_config:
        name: push.autoSetupRemote
        scope: global
        value: 'true'

    - name: User name
      community.general.git_config:
        name: user.name
        scope: global
        value: Martin Othamar

    - name: User email
      community.general.git_config:
        name: user.email
        scope: global
        value: martin@othamar.net
