---
- name: Configure inotify sysctl limits
  hosts: localhost
  become: true
  vars:
    sysctl_config:
      fs.inotify.max_user_instances: 16384
      user.max_inotify_instances: 16384

  tasks:
    - name: Configure sysctl
      ansible.posix.sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        state: present
        sysctl_file: /etc/sysctl.d/local.conf
        reload: true
      with_dict: '{{ sysctl_config }}'
