---
- hosts: localhost
  name: Install Brave browser
  become: true
  tasks:
    - name: Install deps
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: present

    # Ref: https://github.com/ansible/ansible/issues/78063
    - name: Add repo using key from URL
      ansible.builtin.deb822_repository:
        name: brave-browser
        types: deb
        uris: https://brave-browser-apt-release.s3.brave.com
        suites: 'stable'
        components: main
        architectures: amd64
        signed_by: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

    - name: Install Brave browser
      ansible.builtin.apt:
        name:
          - brave-browser
        state: present
        update_cache: true
