---
- name: Install Docker
  hosts: localhost
  become: true
  gather_facts: yes
  tasks:
    - name: Install deps
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
          - python3-debian
        state: present

    # Ref: https://github.com/ansible/ansible/issues/78063
    - name: Add repo using key from URL
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: "{{ ansible_distribution_release }}"
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/ubuntu/gpg

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Create "docker" group
      ansible.builtin.group:
        name: "docker"
        state: present

    - name: Add user to "docker" group
      # NOTE: when run with -K it is run as sudo
      # might still have to
      # `sudo usermod -aG docker $USER` afterwards
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        groups: ["docker"]
        append: true

    - name: Make sure Docker is running
      ansible.builtin.systemd:
        state: started
        name: docker
