---
- name: Install golang
  hosts: localhost
  become: true

  tasks:
    - name: Get latest version
      ansible.builtin.set_fact:
        new_version: "{{ lookup('ansible.builtin.url', 'https://golang.org/VERSION?m=text', split_lines=True, wantlist=True) | first }}"

    - name: Debug
      ansible.builtin.debug:
        msg:
          - "Latest version: '{{ new_version }}'"

    - name: Remove existing go installation
      ansible.builtin.file:
        path: /usr/local/go/
        state: absent

    - name: Download
      ansible.builtin.get_url:
        url: "https://go.dev/dl/{{ new_version }}.linux-amd64.tar.gz"
        dest: "/tmp/{{ new_version }}.linux-amd64.tar.gz"
        mode: '0644'
        force: 'yes'

    - name: Unpack
      ansible.builtin.unarchive:
        src: "/tmp/{{ new_version }}.linux-amd64.tar.gz"
        dest: /usr/local

    - name: Add to path
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: "export PATH=\"$PATH:/usr/local/go/bin\""
        state: present
        insertafter: EOF

    - name: Add $GOPATH/bin to path
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: "export PATH=\"$PATH:{{ lookup('env', 'HOME') }}/go/bin\""
        state: present
        insertafter: EOF
