---
- name: Install/update Rust
  hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Install nightly toolchain
      register: nightly_install
      changed_when: "'unchanged' not in nightly_install.stdout"
      ansible.builtin.command: rustup toolchain install nightly

    - name: Update self
      register: self_update
      changed_when: "'unchanged' not in self_update.stdout"
      ansible.builtin.command: rustup self update

    - name: Update stable
      register: stable_update
      changed_when: "'unchanged' not in stable_update.stdout"
      ansible.builtin.command: rustup update stable

    - name: Update nightly
      register: nightly_update
      changed_when: "'unchanged' not in nightly_update.stdout"
      ansible.builtin.command: rustup update nightly
